config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'profile', to: 'users#profile'

  # get'search_a_nanny', to: 'users#search_a_nanny'
  get 'nanny_index', to: 'users#nanny_index'

  # A supprimer ??
  get 'dashboard', to: 'users#dashboard'

  #création d'une nouvelle route pour avoir un url de type /users/1 qui redirige vers la page dashboard
  get '/users/:id', to: 'users#dashboard', as: 'user'

  get 'messages', to: 'pages#messages'


  resources :nannies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :booking
  # get 'booking', to: 'users#booking'

  # root "bookings#index"

  # resources :users do
  #   resources :nannies
    resources :bookings
  # end

  resources :nannies do
    resources :bookings, only: [ :new, :create, :show ]
  end


end

app/models/nanny.rb
class Nanny < ApplicationRecord
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/nannies_controller.rb
class NanniesController < ApplicationController
  def index
    @user = current_user
    @nannies = Nanny.all
    @nannies = policy_scope(Nanny).order(created_at: :desc)

    @markers = @nannies.geocoded.map do |nanny|
      {
        lat: nanny.latitude,
        lng: nanny.longitude,
        info_window: render_to_string(partial: "info_window", locals: { nanny: nanny }),
        image_url: helpers.asset_url("mama.png")
      }
    end
  end

  def new
    @user = current_user
    @nanny = Nanny.new
    authorize @nanny
  end

  def create
    @nanny = Nanny.new(nanny_params)

    @user = current_user
    @nanny.user = current_user
    authorize @nanny

    if @nanny.save
      redirect_to nannies_path
    else
    end
  end

  def edit
    @user = current_user
    @nanny = Nanny.find(params[:format])
    authorize @nanny
  end

  def update
    @nanny = Nanny.find(params[:id])

    @user = current_user
    @nanny.user = @user
    authorize @nanny

    if @nanny.update(nanny_params_update)
      redirect_to nannies_path
    else
    end
  end

  def destroy
    @nanny = Nanny.find(params[:format])
    authorize @nanny

    if @nanny.destroy
      redirect_to nannies_path
    else
    end
  end

  private

  def nanny_params
    params.require(:nanny).permit(:first_name, :last_name, :tel, :price_per_day, :photo, :email, :address, :description)
  end

  def nanny_params_update
    params.require(:nanny).permit(:price_per_day, :address, :description, :email)
  end
end

app/views/nannies/_info_window.html.erb
<h4 class="fullname"><%= nanny.first_name %> <%= nanny.last_name %></h4>
<p><%= nanny.address %></p>
<p><b><%= nanny.price_per_day %> £</b></p>
<p><%= link_to "Book", new_nanny_booking_path(nanny), class:"bookwindow" %></p>

app/views/nannies/edit.html.erb
<h2> Edit Nanny's profile  <i class="fa-sharp fa-solid fa-user-pen"></i></h2>
<br>
<%# <h4>Selected nanny:</h4> %>

<div class="nanny-edition">


    <div class="selected-nanny">
      <%= cl_image_tag @nanny.photo.key, height: 150, width: 150, crop: :fill %>

      <div class="bloc-nanny">
        <h2> <%= @nanny.first_name %> <%= @nanny.last_name %></h2>
        <ul>
            <%# <li>Created by user id : <%= @nanny.user.id %>
            <%# <li>Nanny id n°:<%= @nanny.id %>
          <li><i class="fa-solid fa-location-dot"></i> <b>  Address</b> :<%= @nanny.address %>
          <li><i class="fa-solid fa-at"></i> <b>  Email</b> :<%= @nanny.email %>
          <li><i class="fa-solid fa-dollar-sign"></i> <b>  Price per day </b>: <%= @nanny.price_per_day %></li>
          <li><i class="fa-solid fa-user"></i> <b>  Description</b> :<%= @nanny.description %></li>
        </ul>
      </div>
    </div>

    <br>

    <div class="edit-nanny-form">
        <h3> Modify your profile here :</h3>
        <br>

        <%# remmplacer @user par @nanny, faut changer toutes les routes pour le create et le new %>

        <%= simple_form_for [@nanny] do |f| %>
          <%= f.input :photo, as: :file %>
          <%= f.input :address %>
          <%= f.input :email %>
          <%= f.input :description %>
          <%= f.input :price_per_day %>

          <%= f.button :submit %>

        <% end %>
    </div>



</div>
<br>
<br>

 <%= link_to "Back to index", nannies_path, class:"edit-page-link" %>
 <br>
 <br>

app/views/nannies/index.html.erb
<%# <%= @markers %>




<h1 class="title">All the Nannies :</h1>
<br>

<div class="search">


  <div class= "result">

        <% @nannies.each do |nanny| %>

          <div class="nanny-card">

            <div class="profimg">
              <% if nanny.photo.attached?%>
                <%= cl_image_tag nanny.photo.key, height: 150, width: 150, crop: :fill %>
              <%else %>
              <% image_tag 'holder.png' %>
              <%end %>
            </div>



            <%# <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661784842/holder_fuevmf.png", :width=>160, :height=>160, :crop=>"fill")%>
            <div class="info">
              <p class="my-nanny">
                <% if nanny.user == current_user %>
                my nanny <i class="fa-solid fa-image-portrait"></i>
                <%end%>

              </p>
              <ul>



                <li class="firstname"> <%= nanny.first_name %></li>
                <li class="lastname"> <%= nanny.last_name %></li>
                <br>
                <li> <%= nanny.email %></li>
                <br>
                <li class="li-address"> <i class="fa-solid fa-location-pin"></i> <%= link_to nanny.address %></li>
                <hr>
                <li> <%= nanny.description %></li>
                <hr>
                <li class="price">Price per day : <br> <b><%= nanny.price_per_day %> £</b></li>

              </ul>
            </div>
                <%#<li>nanny id : <%= nanny.id %>
                <br>

                <%# <li>created by user id : <%= nanny.user.email%>


              <div class="prof-links">
                  <% if nanny.user == current_user %>
                  <%= link_to "Edit", edit_nanny_path(nanny.user.id, nanny.id), class:"edit" %>
                  <br><br>
                  <%= link_to "Delete", nanny_path(nanny.user.id, nanny.id), method: :delete, data: { confirm: "Are you sure?" }, class:"delete" %>
                  <% else %> <br>
                  <%= link_to "👉 Book", new_nanny_booking_path(nanny), class:"book" %></li>
                  <% end %>
              </div>

          </div>
        <% end %>

  </div>


  <%# <div class="map"> %>

    <%# <div class="search-form">
      <%# #barre de recherche %>


    <%# </div> %>

    <div style="width: 100%; height: 500px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <%# </div> %>

</div>

<br>
<br>
<br>
<%# <div class="buttons">
  <%= link_to "Home", dashboard_path, class:"button" %>
   <%# <%= link_to "Search", dashboard_path, class:"button" %>
<%# </div> %>

app/views/nannies/new.html.erb
<%# <h2>Your notifications</h2>

 %>
 <div class="background">

  <div >
    <br>
    <br>

    <div class="headline">
      <h2> Create your Nanny's profile</h2>
      <br>
      <h5>Please fill in the following form :</h5>

    </div>

    <br>

    <div class="form">
      <div class ="col-sm-12 ">

        <%= simple_form_for @nanny do |f| %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :photo, as: :file %>
          <%= f.input :email %>
          <%= f.input :address,
          input_html: { data: { geocoder_target: "address" }, class: "d-none" },
            wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
          <%= f.input :description%>
          <%= f.input :tel %>
          <%= f.input :price_per_day %>
          <br>
          <%= f.button :submit %>
        <% end %>
      </div>

    </div>

  </div>

  <%# <div  class="links">
    <%= link_to "Back", :back %>
  <%# </div> %> 

</div>