config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'profile', to: 'users#profile'

  # get'search_a_nanny', to: 'users#search_a_nanny'
  get 'nanny_index', to: 'users#nanny_index'

  # A supprimer ??
  get 'dashboard', to: 'users#dashboard'

  #création d'une nouvelle route pour avoir un url de type /users/1 qui redirige vers la page dashboard
  get '/users/:id', to: 'users#dashboard', as: 'user'

  get 'messages', to: 'pages#messages'


  resources :nannies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :booking
  # get 'booking', to: 'users#booking'

  # root "bookings#index"

  # resources :users do
  #   resources :nannies
    resources :bookings
  # end

  resources :nannies do
    resources :bookings, only: [ :new, :create, :show ]
  end


end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :nanny  


  validate :after_today
  validate :after_start_date

  def after_today
    unless start_date > Date.today
      errors.add(:start_date, "should be after today")
    end
  end

  def after_start_date
    unless end_date >= start_date
      errors.add(:end_date, "must be the same or after your start day")
    end
  end 
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = current_user
    @bookings = Booking.all
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @user = current_user
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @nanny = Nanny.find(params[:nanny_id])
    @user = current_user
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @nanny = Nanny.find(params[:nanny_id])
    @user = current_user
    @booking.user = current_user
    authorize @booking

      if @booking.save
         redirect_to bookings_path
      else
        render :new
      end
  end

  def edit
    @user = current_user
    @booking = Booking.find(params[:format])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])

    @user = current_user
    @booking.user = @user
    authorize @booking

    if @booking.update(booking_params_update)
      redirect_to booking_path
    else
        render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:format])
    authorize @booking

    if @booking.destroy
      redirect_to bookings_path
    else
    end
  end

    private

  def booking_params
    params.require(:booking).permit(:end_date, :start_date, :nanny_id)
  end

  def booking_params_update
    params.require(:booking).permit(:end_date, :start_date)
  end
end

app/views/bookings/edit.html.erb
<h1 class="right-text"> Edit your Reservation  <i class="fa-sharp fa-solid fa-user-pen"></i></h1>

<div class="edit-booking-box">

  <div class="recap">

    <h2> Booking details:</h2>
    <ul>
        <li><i class="fa-solid fa-book"></i> Booking n°: <b><%= @booking.id %></b></li>
        <li class="bookdate"><i class="fa-sharp fa-solid fa-calendar"></i> From : <b><%= @booking.start_date %></b></li>
        <li class="bookdate"><i class="fa-solid fa-building-circle-check"></i> To : <b><%= @booking.end_date %></b></li>
        <li><i class="fa-solid fa-user"></i> Nanny's name : <b><%= @booking.nanny.first_name %> <%= @booking.nanny.last_name %></b></li>
        <li><i class="fa-solid fa-tag"></i> Nanny n°: <b><%= @booking.nanny.id %></b></li>
    </ul>

  </div>


  <div class="changes">

    <h4 class="update-field">Please update your booking :</h4>

    <%# remmplacer @user par @nanny, faut changer toutes les routes pour le create et le new %>
    <%= simple_form_for [@nanny, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.button :submit %>
    <% end %>

  </div>

</div>


 <div class="backtoindex">
    <%= link_to "Back to index", bookings_path %>
  </div>

app/views/bookings/index.html.erb
<h1 class="right-text">Past & Incoming Reservations</h1>
<div class="result-index">
  <% @bookings.each do |booking| %>
  <div class="index-booking">
  <br>
    <li><%= link_to "Reservation n°", booking_path(booking.id) %> <%= booking.id %></li>
    <br/>
    <li> <i class="fa-solid fa-hand-holding-dollar"></i> Price par day : <%= booking.nanny.price_per_day %>
    <li> <i class="fa-solid fa-calendar-days"></i> Start date : <%=  booking.start_date %></li>
    <li> <i class="fa-solid fa-calendar-days"></i> End date : <%= booking.end_date %></li>
    <li> <i class="fa-duotone fa-signal-bars"></i> Status : <%= booking.status %></li>
    <li> Total price : <%= (booking.end_date.mjd - booking.start_date.mjd + 1) * booking.nanny.price_per_day %>€</li>
    <br>
    <div class="prof-links-index">
    <% if booking.user == current_user %>
    <%= link_to "Edit the booking", edit_booking_path(booking.user.id, booking.id) %>
    </div>
    <br>
    <div class="prof-links-index">
    <%= link_to "Cancel", booking_path(booking.user.id, booking.id), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    </div>
  </div>
    <% end %>
</div>

app/views/bookings/new.html.erb
 <div class="container-booking">

    <div class="nanny-choice">
        <h3>Your super nanny</h3>
        <p class="price"> PRICE PER DAY : <b> <%= @nanny.price_per_day %> £</b></p>
        <hr>
        <p>NANNY n°: <b><%= @nanny.id %></b></p>
        <hr>
        <p> NAME : <b><%= @nanny.first_name %></b>  <b><%=  @nanny.last_name %></b></p></p>
        <hr>
        <%# <p>LAST NAME :
        <hr> %>
    </div>

      <div class="form-info">
        <h3 class="booking-title">Book Here!</h3>

          <%= simple_form_for [@nanny, @booking] do |f| %>

          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.input :nanny_id, input_html: {value: params[:nanny_id]} %>
          <%= f.button :submit %>

        <% end %>
     </div>
  </div>

app/views/bookings/show.html.erb
<%# <div>
    <h1>Booking <strong>n°</b><%= @booking.id %>

<h1 class="right-text"> Your reservation  <i class="fa-sharp fa-solid fa-user-pen"></i></h1>

<div class="delete-booking">
     <div class="recap-booking">

<h2>Nanny Informations</h2>
<br>
<div class="info-text">
<p><i class="fa-solid fa-tag"></i> Nanny n° : <b><%= @booking.nanny.id %></p></b>
<hr>
<p><i class="fa-solid fa-user"></i> Nanny Name : <b><%= @booking.nanny.first_name %> <%= @booking.nanny.last_name %></p></b>
<hr>
<p><i class="fa-solid fa-pencil"></i> Nanny description : <b><%= @booking.nanny.description %></b></p>
<hr>
<p><i class="fa-solid fa-money-bill"></i> Nanny Price per day : <b><%= @booking.nanny.price_per_day%>€</b></p>
<hr>
</div>
    </div>


<div class="date-booking">
    <h2>Dates 🗓️</h2>
        <style type="text/css">
        .tg  {border-collapse:collapse;border-spacing:0;}
        .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        overflow:hidden;padding:10px 5px;word-break:normal;}
        .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
        font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
        .tg .tg-baqh{text-align:center;vertical-align:top}
    .tg .tg-0lax{text-align:left;vertical-align:top}
        </style>
<br>
    <p><i class="fa-sharp fa-solid fa-calendar"></i> From : <b><%= @booking.start_date %></b></p>
    <p><i class="fa-solid fa-building-circle-check"></i> To : <b><%= @booking.end_date %></b></p>
</div>

<br>


<div class="price-booking">
    <h2>Total Price 💸</h2>
    <p><%= (@booking.end_date.mjd - @booking.start_date.mjd + 1) * @booking.nanny.price_per_day %> €</p>
</div>


 <div class="backtoindex">
<%= link_to "Back to bookings", bookings_path %>
</div>
</div>