config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'profile', to: 'users#profile'

  # get'search_a_nanny', to: 'users#search_a_nanny'
  get 'nanny_index', to: 'users#nanny_index'

  # A supprimer ??
  get 'dashboard', to: 'users#dashboard'

  #création d'une nouvelle route pour avoir un url de type /users/1 qui redirige vers la page dashboard
  get '/users/:id', to: 'users#dashboard', as: 'user'

  get 'messages', to: 'pages#messages'


  resources :nannies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :booking
  # get 'booking', to: 'users#booking'

  # root "bookings#index"

  # resources :users do
  #   resources :nannies
    resources :bookings
  # end

  resources :nannies do
    resources :bookings, only: [ :new, :create, :show ]
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :nannies, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # def after_sign_in_path_for(resource)  
  #   user_path(current_user)
  # end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end

  def dashboard
    @user = current_user
    authorize @user
  end

  def dashboarddd
    @user = User.find(params[:id])
    authorize @user
  end
end

app/views/users/dashboard.html.erb
<div class="top">
  <h1><i class="fa-regular fa-calendar-days"> </i> My Dashboard </h1>
  <%# <h1 class="blue"> Nanny & Kids </h1> %>
</div>


<%# Box with ALL divs = dash %>
<div class="dash">
  <%# Box with (Profile div + calendar div) = side %>
  <div class="side">

    <div class="profile">
      <h3>My profile</h3>
      <%# <img class="avatar"src="avatar Ophe.jpg" alt="user pic"> %>
      <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661771495/Nanny%20N%20Kids/avatar_Ophe_uar2wv.jpg", :width=>150, :height=>150, :radius=>"50px", :crop=>"fill")%>

      <br>
      <br>


      <%# <%= link_to 'Edit profile', "#" %>
       <%# <div id="current_date"></p>
          <script>
          document.getElementById("current_date").innerHTML = Date();
          </script> %>
      <br>
      <ul class="notif">
        <li class="mail">Logged as :
            <span class="blue-mail"><u><% if user_signed_in? %>
            <%= current_user.email %>
            <% end %></u></span>
        </li>
        <br>
        <br>
        <br>

        <%# <li><i class="fa-solid fa-gear"></i><a href="#">Edit profile</a></li> %>
        <li><i class="fa-solid fa-gear"></i><%= link_to "Edit profile", "#" %></li>
        <br>
        <li><i class="fa-solid fa-right-from-bracket"></i><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>

    <div class="callendar">
      <%# <p>Add a callendar plug in HERE</p> %>
      <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661528801/Nanny%20N%20Kids/Sans_titre_18_e1dgmd.png",
          width: 200, crop: :fill)%>

    </div>
  </div>


  <%# Box with dashboard actions = container %>
   <div class="container-dash">
    <div class="cards_family">
       <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661528068/Nanny%20N%20Kids/Sans_titre_13_qqmbyk.png",
          width: 190, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Family</h2>
          <p>You need a Nanny ?</p>
          <p>Check out all the Nannies profiles !</p>
          <p>Start your search</p>
          <br>
          <%# <a href="#"class="find-nanny">Find a Nanny</a> %>
          <%= link_to 'Find a Nanny', nannies_path %>
        </div>
    </div>

    <div class="cards_nanny">
      <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661528260/Nanny%20N%20Kids/Sans_titre_11_pn5dve.png",
            width: 140, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Nanny</h2>
          <p>You wanna propose your services ? </p>
          <p> Look around and find a family</p>
          <br>
          <%= link_to "Babysit", new_nanny_path %>
        </div>
    </div>

    <div class="cards_bookings">
      <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661528368/Nanny%20N%20Kids/Sans_titre_15_fwvbeh.png",
            width: 140, crop: :fill)%>
        <div class="card-action">
          <h2>Bookings</h2>

          <p>Take a look at your past <br>and incoming reservations</p>
          <br>

          <%= link_to "View", bookings_path %>
          <br>
        </div>
    </div>

    <div class="cards_mess">
      <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661528441/Nanny%20N%20Kids/Sans_titre_14_ytj7p2.png",
            width: 240, crop: :fill)%>
        <div class="card-action">
          <h2>Messages</h2>
          <p>Check out your conversation feed</p>
          <br>
          <%= link_to "Go", messages_path %>
          <%# <a href="#">Go</a> %>
        </div>
    </div>
  </div>


</div>

<div class= 'footer'>
  <p class="follow">Follow Us !</p>
  <ul>
    <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
  </ul>
  <p class="info">Nanny N Kids - 18, Marble Street - LONDON </p>
  <p>Copyright nannynkids.herokuapp.com - All rights reserved.
  <a href="#">contact@nannynkids.com</a></p>
</div>

app/views/users/dashboarddd.html.erb
<%# ##### A supprimer %>

<div class="top">
  <h1><i class="fa-regular fa-calendar-days"> </i> My Dashboard </h1>
  <h1 class="blue"> Nanny & Kids </h1>
</div>
<%# #ca marche passsssss# %>
<div class="welcome">
  <%# <% if user_signed_in? %>
    <h3>Logged as user N°: <%= @user.id %></h3>
  <%# <% end %>
</div>

<div class="dash">
   <div class="side">
    <h3>User profile</h3>
    <img class="avatar"src="https://via.placeholder.com/150" alt="user pic">
    <p>Sunday, 21st August 2022</p>
    <ul class="notif">
      <li><i class="fa-solid fa-bell"></i><a href="#">Notifications</a></li>
      <li><i class="fa-solid fa-gear"></i><a href="#">Settings</a></li>
      <li><i class="fa-solid fa-right-from-bracket"></i><%= link_to "Log out", root_path %></li>
    </ul>
  </div>

  <div class="container">
    <div class="cards">
        <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661087828/Nanny%20N%20Kids/urafamily_p3o3ed.jpg",
          width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Family</h2>
          <p>You need a Nanny ? click <strong>here</strong> to start your search.</p>
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661087828/Nanny%20N%20Kids/urananny_e9e0pj.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Nanny</h2>
          <p>You wanna propose your services ? click <strong>here</strong> and find a family.</p>
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661089186/Nanny%20N%20Kids/jeshoots-com-9n1USijYJZ4-unsplash_bb0se0.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>Bookings</h2>
          <p>Take a look at your <br><br><%= link_to "Past & incoming reservations.", user_bookings_path(@user.id) %></p>
          
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661089353/Nanny%20N%20Kids/jeshoots-com-Lu9FNRCqPys-unsplash_hszuse.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>Messages</h2>
          <p>Check out your <strong>conversation feed</strong>.</p>
        </div>
    </div>
  </div>


</div>
<br>
<br>
<br>


<%# <a href="#">Log out</a> %>

app/views/users/profile_ancienne_version.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatarfun.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>