config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'

  get 'profile', to: 'users#profile'

  # get'search_a_nanny', to: 'users#search_a_nanny'
  get 'nanny_index', to: 'users#nanny_index'

  # A supprimer ??
  get 'dashboard', to: 'users#dashboard'

  #création d'une nouvelle route pour avoir un url de type /users/1 qui redirige vers la page dashboard
  get '/users/:id', to: 'users#dashboard', as: 'user'

  get 'messages', to: 'pages#messages'


  resources :nannies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :booking
  # get 'booking', to: 'users#booking'

  # root "bookings#index"

  # resources :users do
  #   resources :nannies
    resources :bookings
  # end

  resources :nannies do
    resources :bookings, only: [ :new, :create, :show ]
  end


end

app/views/pages/dashboard.html.erb
<div class="top">
  <h1><i class="fa-regular fa-calendar-days"> </i> My Dashboard </h1>
  <h1 class="blue"> Nanny & Kids </h1>
</div>

<div class="welcome">
  <% if user_signed_in? %>
    <h3>Logged as:<% current_user.email %></h3>
  <% end %>
</div>

<div class="dash">
   <div class="side">
    <h3>User profile</h3>
    <img class="avatar"src="https://via.placeholder.com/150" alt="user pic">
    <p>Sunday, 21st August 2022</p>
    <ul class="notif">
      <li><i class="fa-solid fa-bell"></i><a href="#">Notifications</a></li>
      <li><i class="fa-solid fa-gear"></i><a href="#">Settings</a></li>
      <li><i class="fa-solid fa-right-from-bracket"></i><%= link_to "Log out", root_path %></li>
    </ul>
  </div>

  <div class="container">
    <div class="cards">
        <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661087828/Nanny%20N%20Kids/urafamily_p3o3ed.jpg",
          width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Family</h2>
          <p>You need a Nanny ? click <strong>here</strong> to start your search.</p>
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661087828/Nanny%20N%20Kids/urananny_e9e0pj.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>You are a Nanny</h2>
          <p>You wanna propose your services ? click <strong>here</strong> and find a family.</p>
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661089186/Nanny%20N%20Kids/jeshoots-com-9n1USijYJZ4-unsplash_bb0se0.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>Bookings</h2>
          <p>Take a look at your <strong>past & incoming</strong> reservations.</p>
        </div>
    </div>

    <div class="cards">
      <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661089353/Nanny%20N%20Kids/jeshoots-com-Lu9FNRCqPys-unsplash_hszuse.jpg",
            width: 100, height: 100, crop: :fill)%>
        <div class="card-action">
          <h2>Messages</h2>
          <p>Check out your <strong>conversation feed</strong>.</p>
        </div>
    </div>
  </div>


</div>
<br>
<br>
<br>


<%# <a href="#">Log out</a> %>

app/views/pages/home.html.erb
<div class= 'banner'>
  <h1> <i class="fa-solid fa-children"></i>   Nanny & Kids   <i class="fa-solid fa-children"></i></h1>

</div>

<%# <div class='CTA'> %>
  <%# <h3>Find your Nanny in one click!</h3>
   <p>An app needed by all families</p> %>

  <%# <a class="btn-succes"href="#">Sign Up</a>
  <a class="btn-succes" href="#">Sign In</a> %>
<%# </div> %>

<div class="landing-img">
   <%= cl_image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661068667/Nanny%20N%20Kids/profiles.jpeg_qmit6f.jpg",
      width: 700, height: 400, crop: :fill)%>

  <h3>
    <span style="color: #7897ab">
      Find your Nanny in one click!
    </span>
    <br><br>
      Check out the nannies profiles, <br> Propose your services <br><br>
        <span class ="btn-succes">
          <a href="#">Sign Up</a>
        </span>
        <span class ="btn-succes">
          <%= link_to "Sign in", dashboard_path %>
        </span>
  </h3>
</div>

<div class= 'footer'>
  <p class="follow">Follow Us !</p>
  <ul>
    <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
  </ul>
  <p class="info">Nanny N Kids - 18, Marble Strett - LONDON </p>
  <p>Copyright nannynkids.herokuapp.com - All rights reserved.
  <a href="#">contact@nannynkids.com</a></p>
</div>

app/views/pages/landing.html.erb
<%# <div class= 'banner'>
  <h1> <i class="fa-solid fa-children"></i>   Nanny & Kids   <i class="fa-solid fa-children"></i></h1>

</div> %>

<%# <div class='CTA'> %>
  <%# <h3>Find your Nanny in one click!</h3>
   <p>An app needed by all families</p> %>

  <%# <a class="btn-succes"href="#">Sign Up</a>
  <a class="btn-succes" href="#">Sign In</a> %>
<%# </div> %>

<div class="landing-img">
  <%= image_tag("https://res.cloudinary.com/dhxefoe7j/image/upload/v1661068667/Nanny%20N%20Kids/profiles.jpeg_qmit6f.jpg",
      width: 700, height: 400, crop: :fill)%>

  <h3>
    <span style="color: #7897ab">
      Find your Nanny in one click!
    </span>
    <br><br>
      Check out the nannies profiles, <br> Propose your services <br><br>
        <span class ="btn-succes">
          <%# <a href="#">Register</a> %>
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </span>
        <span class ="btn-succes">
         <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </span>
  </h3>
</div>

<div class= 'footer'>
  <p class="follow">Follow Us !</p>
  <ul>
    <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
    <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
  </ul>
  <p class="info">Nanny N Kids - 18, Marble Street - LONDON </p>
  <p>Copyright nannynkids.herokuapp.com - All rights reserved.
  <a href="#">contact@nannynkids.com</a></p>
</div>

app/views/pages/messages.html.erb
<h1>Conversation feed</h1>
<br>
<br>


<h4 class="conv">Conversation with <span class="mami">Mamie Suzette.</span></h4>

<div class="total">

  <div class="page-content page-container" id="page-content">
      <div class="padding">
          <div class="row container d-flex justify-content-center">
  <div class="col-md-6">
              <div class="card card-bordered">
                <div class="card-header">
                  <h4 class="card-title"><strong>Chat</strong></h4>
                  <a class="btn btn-xs btn-secondary" href="#" data-abc="true">Let's Chat App</a>
                </div>


                <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important;">
                  <div class="media media-chat">
                    <%= image_tag('https://res.cloudinary.com/dhxefoe7j/image/upload/v1661771495/Nanny%20N%20Kids/avatar_Ophe_uar2wv.jpg', crop: :fill, class:'avatarr') %>
                    <div class="media-body">
                      <p>Hi</p>
                      <p>How are you ...???</p>
                      <p>What are you doing tomorrow?<br> Can you watch for Andrea in the morning?</p>
                      <p class="meta"><time datetime="2018">23:58</time></p>
                    </div>
                  </div>

                  <div class="media media-meta-day">Today</div>

                  <div class="media media-chat media-chat-reverse">
                    <div class="media-body">
                      <p>Hiii, I'm good.</p>
                      <p>How are you doing?</p>
                      <p>No problem for tomorrow! what time?</p>
                      <p class="meta"><time datetime="2018">00:06</time></p>
                    </div>
                  </div>

                  <div class="media media-chat">
                    <%= image_tag('https://res.cloudinary.com/dhxefoe7j/image/upload/v1661857073/Nanny%20N%20Kids/profile5_lybhad.jpg', crop: :fill, class:'avatarr') %>
                    <div class="media-body">
                      <p>Okay</p>
                      <p>Great thank you! 9AM will be perfect! We'll be back at 6PM</p>
                      <p class="meta"><time datetime="2018">00:07</time></p>
                    </div>
                  </div>

                  <div class="media media-chat media-chat-reverse">
                    <div class="media-body">
                      <p>Ok ! Good for me!</p>
                      <p>Do you want me to come over?</p>
                      <p>Or I take Andrea at home?</p>
                      <p class="meta"><time datetime="2018">00:09</time></p>
                    </div>
                  </div>

                  <div class="media media-chat">
                    <%= image_tag('https://res.cloudinary.com/dhxefoe7j/image/upload/v1661771495/Nanny%20N%20Kids/avatar_Ophe_uar2wv.jpg', crop: :fill, class:'avatarr') %>
                    <div class="media-body">
                      <p>We can drive her to your place!</p>
                      <p class="meta"><time datetime="2018">00:10</time></p>
                    </div>
                  </div>

                  <div class="media media-chat media-chat-reverse">
                    <div class="media-body">
                      <p>Ok great!</p>
                      <p class="meta"><time datetime="2018">00:10</time></p>
                    </div>
                  </div>

                  <div class="media media-chat">
                    <%= image_tag('https://res.cloudinary.com/dhxefoe7j/image/upload/v1661857073/Nanny%20N%20Kids/profile5_lybhad.jpg', crop: :fill, class:'avatarr') %>
                    <div class="media-body">
                      <p>See you tomorrow!</p>
                      <p class="meta"><time datetime="2018">00:12</time></p>
                    </div>
                  </div>

                  <div class="media media-chat media-chat-reverse">
                    <div class="media-body">
                      <p>Yep! have a good day!</p>
                      <p class="meta"><time datetime="2018">00:12</time></p>
                    </div>
                  </div>

                <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;"></div></div></div>

                <div class="publisher bt-1 border-light">

                  <%# <img class="avatarr avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png"width ="80px" alt="..."> %>

  < <%= image_tag('https://res.cloudinary.com/dhxefoe7j/image/upload/v1661771495/Nanny%20N%20Kids/avatar_Ophe_uar2wv.jpg', crop: :fill, class:'avatarr') %>

                  <input class="publisher-input" type="text" placeholder="Write something">
                  <span class="publisher-btn file-group">
                    <i class="fa fa-paperclip file-browser"></i>
                    <input type="file">
                  </span>
                  <a class="publisher-btn" href="#" data-abc="true"><i class="fa fa-smile"></i></a>
                  <a class="publisher-btn text-info" href="#" data-abc="true"><i class="fa fa-paper-plane"></i></a>
                </div>

              </div>
            </div>
            </div>
            </div>
            </div>

</div>
<br>
<br>



<div class ="messlink">
  <%= link_to "Home", dashboard_path, class:"homemess" %>
</div>

app/views/pages/profile_old.html.erb
<div class="top">
  <h1><i class="fa-solid fa-user"> </i> My Profile </h1>
  <h1 class="blue"> Nanny & Kids </h1>
</div>

<div class="container">

 <div class="dash">
   <div class="side">
    <h3>Profile</h3>
    <p>Sunday, 21st August 2022</p>
    <img class="avatar"src="https://via.placeholder.com/150" alt="user pic">
    <p>Full name</p>
    <ul class="notif">
      <li><i class="fa-solid fa-location-dot"></i><a href="#">9 rue de la Paix, Paris</a></li>
      <li><i class="fa-solid fa-at"></i><a href="#">mail@mail.com</a></li>
      <li><i class="fa-solid fa-phone"></i><a href="#">00 66 77 88 99</a></li>
    </ul>
    </div>

        <%= form_for :user, url: user_index_path do |f| %>
        <div class="last_name">
          <p>
            <%= f.label :last_name %><br>
            <%= f.text_field :last_name %>
          </p>
           <p>
            <%= f.submit :Update %>
          </p>
         </div>
          <p>
            <%= f.label :first_name %><br>
            <%= f.text_field :first_name %>
          </p>

          <p>
            <%= f.label :address %><br>
            <%= f.text_area :address %>
          </p>
         <p>
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </p>
         <p>
            <%= f.label :phone %><br>
            <%= f.text_field :phone %>
          </p>
          <p>
            <%= f.submit :Update %>
          </p>
        <% end %>

</div>

<%# <div class="text-center">
   <button type="button" class="btn btn-dark">Switch to Nanny Profile</button>
 </div> %>
<%# <ul class="notif">
      <li><i class="fa-solid fa-bell"></i><a href="#">Notifications</a></li>
      <li><i class="fa-solid fa-gear"></i><a href="#">Settings</a></li>
      <li><i class="fa-solid fa-right-from-bracket"></i><%= link_to "Log out", root_path %></li>
    <%# </ul> %>